### ISSUE TITLE
CDN down?

### ISSUE THREAD

**Issue by ppazos** [MrSwitch/jquery.form.js#6]
I´m testing it and on the console I see 

Failed to load resource: the server responded with a status of 404 (Not Found)
https://cdn.syndication.twitter.com/widgets/tweetbutton/count.json?url=http%3A%2F%2Fadodson.com%2Fjquery.form.js%2F%23the-quick-and-dirty-implementation

From:
http://adodson.com/jquery.form.js/#the-quick-and-dirty-implementation

**Comment by MrSwitch** [comment]
That's a bug in https://github.com/MrSwitch/adorn closing this.. thanks
